site_name: ObserveEarth Documentation
site_description: Simplifying Earth Observation Data Access from Microsoft Planetary Computer
site_author: Krishna Lodha
site_url: https://observearth.readthedocs.io

repo_name: Rotten-Grapes-Pvt-Ltd/observearth-py
repo_url: https://github.com/Rotten-Grapes-Pvt-Ltd/observearth-py

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocs-jupyter

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Tutorials:
    - Basic NDVI: tutorials/basic-ndvi.md
    - Multiple Indices: tutorials/multiple-indices.md
    - Sentinel-2 vs Landsat: tutorials/comparison.md
  - API Reference:
    - Satellites: api/satellites.md
    - Indices: api/indices.md
    - Export: api/export.md
  - Contributing:
    - Setup: contributing/setup.md
    - Guidelines: contributing/guidelines.md
    - Testing: contributing/testing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html